---
fzf_default_install_prefix: "/usr/local"

fzf_default_use_pkg_mgr: false

fzf_default_config_block: |
  if [[ ! "$PATH" == *"{{ fzf_install_prefix }}"bin* ]]; then
    export PATH="$PATH:"{{ fzf_install_prefix }}"bin"
  fi

  if [[ ! "$MANPATH" == *"{{ fzf_install_prefix }}"man* && -d "{{ fzf_install_prefix }}man" ]]; then
    export MANPATH="$MANPATH:"{{ fzf_install_prefix }}"man"
  fi

  [[ $- == *i* ]] && source "{{ fzf_install_prefix }}/shell/completion.{{ ansible_user_shell | basename }}" 2> /dev/null

  source "{{ fzf_install_prefix }}/shell/key-bindings.{{ ansible_user_shell | basename }}"
